"""Backtest quality report contracts."""

from quantitative_sentiment_analysis.backtest_quality.metrics import (
    build_quality_report,
)
from quantitative_sentiment_analysis.backtest_quality.repository import (
    CompletedDatasetQualityInputProvider,
    LOCAL_FIXTURE_PROVIDER,
    LocalFixtureQualityInputProvider,
    NotReadyQualityInputProvider,
    QSA_BACKTEST_QUALITY_PROVIDER,
    QSA_RUNTIME_ENV,
    QualityInputProvider,
    QualityRunIncompleteError,
    QualityRunNotFoundError,
    QualityRunNotReadyError,
    QualityRunUnsupportedError,
    get_quality_input_provider,
)
from quantitative_sentiment_analysis.backtest_quality.schemas import (
    BacktestQualityReport,
    DirectionalBias,
    EvaluationOutcome,
    HorizonUnit,
    QualityInputBatch,
    QualityChartPoint,
    QualityHorizon,
    QualityInputRecord,
    QualityMetrics,
    RealizedDirection,
    RelevanceLabel,
    SUPPORTED_QUALITY_HORIZON_PRESETS,
    UnsupportedQualityHorizonError,
    supported_quality_horizon,
)

__all__ = [
    "BacktestQualityReport",
    "CompletedDatasetQualityInputProvider",
    "DirectionalBias",
    "EvaluationOutcome",
    "HorizonUnit",
    "LOCAL_FIXTURE_PROVIDER",
    "LocalFixtureQualityInputProvider",
    "NotReadyQualityInputProvider",
    "QSA_BACKTEST_QUALITY_PROVIDER",
    "QSA_RUNTIME_ENV",
    "QualityChartPoint",
    "QualityHorizon",
    "QualityInputBatch",
    "QualityInputProvider",
    "QualityInputRecord",
    "QualityMetrics",
    "QualityRunIncompleteError",
    "QualityRunNotFoundError",
    "QualityRunNotReadyError",
    "QualityRunUnsupportedError",
    "RealizedDirection",
    "RelevanceLabel",
    "SUPPORTED_QUALITY_HORIZON_PRESETS",
    "UnsupportedQualityHorizonError",
    "build_quality_report",
    "get_quality_input_provider",
    "supported_quality_horizon",
]
