import type { BacktestQualityReport } from "./types";

export const backtestQualityReport: BacktestQualityReport = {
  workspace_id: "workspace-alpha",
  run_id: "run-001",
  instrument: "BTCUSD",
  mode: "BACKTEST",
  horizon: { value: 4, unit: "hours" },
  model_version: "sentiment-rules-v1",
  config_version: "quality-config-v1",
  metrics: {
    correlation: 0.997,
    hit_rate: 0.75,
    sample_count: 4,
    correlation_pair_count: 3,
    hit_count: 3,
    miss_count: 1,
    missing_movement_count: 1,
    flat_count: 1,
    noise_count: 1,
  },
  warnings: [
    "1 record(s) missing later movement were counted as misses.",
    "1 noise/irrelevant record(s) were preserved but excluded from metric denominators.",
  ],
  chart_points: [
    {
      event_timestamp: "2026-06-08T12:01:00Z",
      sentiment_score: 0.8,
      later_return: 0.04,
      directional_bias: "LONG",
      realized_direction: "UP",
      confidence: 0.75,
      outcome: "HIT",
    },
    {
      event_timestamp: "2026-06-08T12:02:00Z",
      sentiment_score: -0.6,
      later_return: -0.03,
      directional_bias: "SHORT",
      realized_direction: "DOWN",
      confidence: 0.75,
      outcome: "HIT",
    },
    {
      event_timestamp: "2026-06-08T12:03:00Z",
      sentiment_score: 0,
      later_return: 0,
      directional_bias: "FLAT",
      realized_direction: "FLAT",
      confidence: 0.75,
      outcome: "HIT",
    },
    {
      event_timestamp: "2026-06-08T12:04:00Z",
      sentiment_score: 0.5,
      later_return: null,
      directional_bias: "LONG",
      realized_direction: null,
      confidence: 0.75,
      outcome: "MISS",
    },
    {
      event_timestamp: "2026-06-08T12:05:00Z",
      sentiment_score: -0.9,
      later_return: -0.02,
      directional_bias: "SHORT",
      realized_direction: "DOWN",
      confidence: 0.75,
      outcome: "EXCLUDED",
    },
  ],
  representative_records: [
    {
      workspace_id: "workspace-alpha",
      run_id: "run-001",
      record_id: "record-001",
      instrument: "BTCUSD",
      mode: "BACKTEST",
      event_timestamp: "2026-06-08T12:01:00Z",
      headline: "BTCUSD quality fixture 1",
      source_id: null,
      source_name: "Example Crypto News",
      sentiment_score: 0.8,
      directional_bias: "LONG",
      confidence: 0.75,
      relevance: "RELEVANT",
      later_return: 0.04,
      realized_direction: "UP",
      model_version: "sentiment-rules-v1",
      config_version: "quality-config-v1",
    },
    {
      workspace_id: "workspace-alpha",
      run_id: "run-001",
      record_id: "record-004",
      instrument: "BTCUSD",
      mode: "BACKTEST",
      event_timestamp: "2026-06-08T12:04:00Z",
      headline: "BTCUSD quality fixture with missing movement",
      source_id: null,
      source_name: "Example Crypto News",
      sentiment_score: 0.5,
      directional_bias: "LONG",
      confidence: 0.75,
      relevance: "RELEVANT",
      later_return: null,
      realized_direction: null,
      model_version: "sentiment-rules-v1",
      config_version: "quality-config-v1",
    },
  ],
};

export const emptyBacktestQualityReport: BacktestQualityReport = {
  ...backtestQualityReport,
  metrics: {
    ...backtestQualityReport.metrics,
    correlation: null,
    hit_rate: null,
    sample_count: 0,
    correlation_pair_count: 0,
    hit_count: 0,
    miss_count: 0,
    missing_movement_count: 0,
    flat_count: 0,
    noise_count: 0,
  },
  warnings: [],
  chart_points: [],
  representative_records: [],
};

export const zeroNumericBacktestQualityReport: BacktestQualityReport = {
  ...backtestQualityReport,
  metrics: {
    ...backtestQualityReport.metrics,
    correlation: null,
    correlation_pair_count: 0,
    hit_count: 0,
    miss_count: 2,
    missing_movement_count: 2,
  },
  warnings: [
    "2 record(s) missing later movement were counted as misses.",
    "2 record(s) missing price movement because the horizon price candle was unavailable.",
  ],
  chart_points: backtestQualityReport.chart_points.slice(0, 2).map((point) => ({
    ...point,
    later_return: null,
    realized_direction: null,
    outcome: "MISS",
  })),
  representative_records: backtestQualityReport.representative_records.map((record) => ({
    ...record,
    later_return: null,
    realized_direction: null,
  })),
};

export const enrichedBacktestQualityReport: BacktestQualityReport = {
  ...backtestQualityReport,
  metrics: {
    ...backtestQualityReport.metrics,
    correlation: 0.998,
    correlation_pair_count: 5,
    hit_count: 4,
    miss_count: 0,
    missing_movement_count: 0,
  },
  warnings: [],
  chart_points: backtestQualityReport.chart_points.map((point, index) => ({
    ...point,
    later_return: point.later_return ?? 0.012 + index * 0.001,
    realized_direction: point.realized_direction ?? "UP",
    outcome: point.outcome === "MISS" ? "HIT" : point.outcome,
  })),
  representative_records: backtestQualityReport.representative_records.map(
    (record, index) => ({
      ...record,
      later_return: record.later_return ?? 0.012 + index * 0.001,
      realized_direction: record.realized_direction ?? "UP",
    }),
  ),
};
